### ISSUE TITLE
6:Chipmunk (cpp-test.exe) is not running, cpp-tests.exe crashed (any hints for me?)

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#114]
- cocos2d-x version: engine-x (latest download 20200728)
- devices test on: Windows 10 Desktop
- developing environments
   - VS version:  2019

Steps to Reproduce:
1.  starts download-deps.py  => downloaded v47.zip 
2.  build cpp-test.exe and start it
6.  select  6. Chipmunk 
7.  cpp-test.exe closed without any info.

**Comment by halx99** [comment]
thanks for your feedback, I will check later.

**Comment by aismann** [comment]
37:Node:Physics is also crashing 
I think it is the same issue:  use the same 2D physics engine: Chipmunk2D

**Comment by halx99** [comment]
Does the box2d works?

**Comment by aismann** [comment]
> 
> 
> Does the box2d works?

Can't say anything about Box2D.
Im using Chipmunk2D on Cocos2Dx 4.0 nativ and it works well.
But I want to switch to engine-x (is modern, faster fixing, etc)

_I can try to use the 37:Node:Physics with Box2D.
@halx99: I will inform you about Box2D and 37:Node:Physics_

Anyhow:
**I like to use Chipmunk2D native sources together with engine-x ;**)

**Comment by aismann** [comment]
Bad news:
nativ Box2D tests be no longer part of cocosd2x 4.0

Copy from cocos2d-x-3.17.2 is not compiling:
...
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	**'GLProgram'**: is not a member of 'cocos2d' (compiling source file ..\Classes\Box2DTestBed\GLES-Render.cpp)	cpp-tests	engine-x-master\tests\cpp-tests\Classes\Box2DTestBed\GLES-Render.h	34	
...

**Comment by halx99** [comment]
ok, got it, let me check what happen

**Comment by aismann** [comment]
if the ChipmunkTest is rrunning again I will use engine-x

**Comment by halx99** [comment]
fixed by: https://github.com/c4games/engine-x/commit/af6cae61ebf2e8ab6928c43e1741d1e610bcf468

**Comment by halx99** [comment]
Since engine-x upgrade chipunk to v7.0.3 other platform lib should be update later

**Comment by aismann** [comment]
Works now.
My own native Chipmunk2D "game" works also with this fixed version of engine-x. 
Thanks.

**Comment by halx99** [comment]
hello @aismann , does the latest Chipmunk2D stable, I see it have commit from you since v7.0.3

**Comment by halx99** [comment]
Update: latest master use source build for chipmunk at all platforms, and should be works well.

**Comment by aismann** [comment]
> hello @aismann , does the latest Chipmunk2D stable, I see it have commit from you since v7.0.3
I using Windows only at the moment sorry.
Androids comes later.

BTW can we have **prebuilt release** versions of the third party libs too?
