### ISSUE TITLE
Issue11942Test::Issue11942Test(): "drawCircle() with width" is not working correct (The second circle has no bigger lines)

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#122]
- cocos2d-x version:  
- devices test on: Windows
- developing environments
   - VS version: 2019
 

Steps to Reproduce:
build and start:     28:Node: Draw

Internal:
seems DrawNode::setLineWidth(width) is not working correct.

**Comment by halx99** [comment]
Does official v4 works?

**Comment by halx99** [comment]
Well, mybe because at windows, engine-x use angleproject GLES, try switch to OpenGL, then check whether setLineWidth(width) works?

**Comment by halx99** [comment]
Just change the macros 'CC_USE_GLES_ON_DESKTOP=0' at CCPlatformConfig.h

**Comment by aismann** [comment]
rebuild and works correct now (on official v4 it works too).
Thanks for the hint.

maybe a snippet like this is usefull?
#if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROIDS)
#define CC_USE_GLES_ON_DESKTOP 1
#else
#define CC_USE_GLES_ON_DESKTOP 0
#endif

**Comment by aismann** [comment]
But I thinke there is a second bug on it:

But circle having the same width, but it shoul be different (on v4 it has the same  behavior)

**Comment by halx99** [comment]
Yeah, maybe bug on angleproject, I will attention on it later.

**Comment by halx99** [comment]
> rebuild and works correct now (on official v4 it works too).
> Thanks for the hint.
> 
> maybe a snippet like this is usefull?
> #if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROIDS)
> #define CC_USE_GLES_ON_DESKTOP 1
> #else
> #define CC_USE_GLES_ON_DESKTOP 0
> #endif
> 
> Information:
> The circle looks very ugly too.

doen't need t adjust platform macros, because on android, always use GLES
