### ISSUE TITLE
Exception thrown at 0x0F63418C (vcruntime140d.dll) in cpp-tests.exe: 0xC0000005: Access violation writing location 0x00000000.

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#127]
Windows 10 Desktop /VS2019

Steps to Reproduce:

1) Start cpp-tests.exe
2) Go to 5:Audio - NewAudioEngine 
3) Go to 19:play, preload, stop switch test
4) Press the "Back" button
=> Crashing

Exception thrown at 0x0F63418C (vcruntime140d.dll) in cpp-tests.exe: 0xC0000005: Access violation writing location 0x00000000.

**Comment by halx99** [comment]
Should be fixed by latest commit

**Comment by aismann** [comment]
Yes. Is fixed.

**Comment by halx99** [comment]
Note: the official v4 also have this same crash problem
