### ISSUE TITLE
Unhandled exception at 0x755849C2 in cpp-tests.exe: Microsoft C++ exception: std::out_of_range at memory location 0x00D8E634.

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#128]
Windows 10 / VS2019

Steps to Reproduce:

1.  Start 38:Node: Physics3D -> press only the right green arrow -> after 5:Physics3D Test => Crashing

Unhandled exception at 0x755849C2 in cpp-tests.exe: Microsoft C++ exception: std::out_of_range at memory location 0x00D8E634.

CCImage.cpp line 815
on bool Image::isCompressed()
{
    return Texture2D::getPixelFormatInfoMap().at(_pixelFormat).compressed;
}

**Comment by aismann** [comment]
Steps to Reproduce:

    Start 38:Node: Physics3D ->Pressing the **left** green arrow is also frozen the cpp-tests.exe

**Comment by halx99** [comment]
thanks for your feedback, does the official v4 works?
I'm in bus at this time

**Comment by aismann** [comment]
v4 works here

**Comment by halx99** [comment]
fixed

**Comment by halx99** [comment]
root cause is libjpeg.lib header mismatch for win32 only
