### ISSUE TITLE
69 Window Test => Full screen is hanging/ Second monitor modus not working

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#129]
Windows 10 / VS2019
Steps to Reproduce:
    Start 69 Window Test -> try all modus -> the second Monitor is not working
On v4 it is working only once (than it is no longer shown)

**Comment by halx99** [comment]
Mybe glfw bugs, I will check next week, my home no double display

**Comment by halx99** [comment]
please check whether the latest commit fix this issue

**Comment by aismann** [comment]
Works now. Thanks.
BTW: I works also on an third monitor too

**Comment by halx99** [comment]
wow, you have so many monitors
