### ISSUE TITLE
Resouce: "wav-samples/8kadpcm.wav" is missed

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#130]
engine-x source:       _audioID = AudioEngine::play2d("wav-samples/8kadpcm.wav", _loopEnabled, _volume);
v4 source:                _audioID = AudioEngine::play2d("background.mp3", _loopEnabled, _volume);

Maybe there is a reason to use "8kadpcm.wav", so I want not send a pull request with "background.mp3"

**Comment by halx99** [comment]
should b mp3, and later I will add a new test case for .wav formats
you can send a pr to fix this.
