### ISSUE TITLE
Seems DrawNode::setLineWidth(>) is not working correct (tested on Windows 10) 

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#137]
Windows 10 / VS2019

Steps to Reproduce:
1) Start: 28:Node: Draw
Both circle having the same width, but it should be different 1 and 10 (on v4 it has the same behavior).

**Comment by aismann** [comment]
More info:
After some tests I see the test have to be rewrite (each DrawNode has it own width, changing it is not working => only the **latest** width will be used on the renderer).

I am right? How is the behavior on android?

I will rewrite the test.

**Comment by halx99** [comment]
Yeah, you are right, I also realized that, I think you can rewrite the test, and guess cocos2d-x v3 also will have the same behavior

**Comment by aismann** [comment]
The test was written for the reason: Issue11942Test::Issue11942Test()
What was the Issue11942?

**Comment by halx99** [comment]
The issue should be the official cocos2d-x repo

**Comment by halx99** [comment]
https://github.com/cocos2d/cocos2d-x/issues/11942

**Comment by halx99** [comment]
so the behavior maybe what they are want.
