### ISSUE TITLE
void DrawNode::setLineWidth(float lineWidth)  supports only thickness between 1...7 (and setLineWidth(x) draws a "linewidth x-1"  

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#139]
Windows 10 / VS2019

Steps to Reproduce:

DrawNode::setLineWidth(0); and  DrawNode::setLineWidth(1); draws a line width 1

DrawNode::setLineWidth(x); draws a line width x-1

**Maybe an hint like the snippet below is usefull?**

void DrawNode::setLineWidth(float lineWidth)
{
    if (lineWidth <= 0)
    {
        CCLOG("DrawNode::setLineWidth(%f) is not realy usefull.", lineWidth);
    }
    else if(lineWidth > 7) // lineWidth > 7 is not correct drawn
    {
        CCLOG("DrawNode::setLineWidth(%f) is out of supported width 1...7.", lineWidth);
    } 
    _lineWidth = lineWidth + 1.0f;
}

float DrawNode::getLineWidth()
{
    return _lineWidth -1.0f;
}

**Comment by aismann** [comment]
...add least on debug modus

**Comment by halx99** [comment]
Switch to OpenGL can check this different behavior

**Comment by aismann** [comment]
> 
> 
> Switch to OpenGL can check this different behavior

How?

**Comment by halx99** [comment]
Modify the macro ```CC_USE_GLES_ON_DESKTOP``` to ```0``` at ```cocos/platform/CCPlatformConfig.h```

**Comment by aismann** [comment]
#define CC_USE_GLES_ON_DESKTOP 0  =>  it has no thickness. OpenGL works not with thickness.
#define CC_USE_GLES_ON_DESKTOP 1  =>  shows the behavior as I has written above

**Comment by halx99** [comment]
Does the official v3 works well?

**Comment by aismann** [comment]
3.17.2 on windows shows the behavior as I has written above (only 0 is different=> 0 ==7pixel)

**Comment by halx99** [comment]
the line width at least 1px, see:
```cpp
void CommandBufferGL::setLineWidth(float lineWidth)
{
    if(lineWidth > 0.0f)
        glLineWidth(lineWidth);
    else
        glLineWidth(1.0f);
    
}
```

**Comment by aismann** [comment]
Yes, that's correct it is on line 606 on CommandBufferGL.cpp.
That's the reason why a setLineWidth(0) has a thickness of 1 on engine-x
On 3.17.2 isn't this line.

**Comment by aismann** [comment]
I have found the reason of supported thickness 1-7 points:

    GLint range[2];
    glGetIntegerv(GL_ALIASED_LINE_WIDTH_RANGE, range);

returning 1,7
so it is clear that's my system only drawing a thickness between 1-7

Maybe it should be part of the documentation.

**Comment by aismann** [comment]
Here are more info for the documentation:
On my system (another system maybe having another min/max) :
CC_USE_GLES_ON_DESKTOP 1   has a supported min/max width of 1/1  
CC_USE_GLES_ON_DESKTOP 0   has n supported min/max width of 1/7

**Comment by halx99** [comment]
seems googles angle renderer doesn't support non-1 line width.
