### ISSUE TITLE
32:Node:MotionStreak shows heavy artefacts

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#143]
Windows10/VS2019

Steps to Reproduce:

#define "CC_USE_GLES_ON_DESKTOP 1"
1.  start 32:Node:MotionStreak
2.  see screenshot below  => with "CC_USE_GLES_ON_DESKTOP 0" there is the cloud without the gray "arrows/lines"

![32_Node_MotionStreak](https://user-images.githubusercontent.com/8652787/89372771-54fede00-d6e7-11ea-9c46-44732e69a951.png)

**Comment by aismann** [comment]
seems the OpenGL drivers works better as  "angle" on my maschine.

**Comment by aismann** [comment]
Maybe it is better to set the default to:
#define "CC_USE_GLES_ON_DESKTOP 0"

and write an hint on the descripton too (artefacts and line width)

**Comment by halx99** [comment]
I have test on android, have the same problem, so I think, maybe it's caused by some incompatible with OpenGL ES

**Comment by halx99** [comment]
> Maybe it is better to set the default to:
> #define "CC_USE_GLES_ON_DESKTOP 0"
> 
> and write an hint on the descripton too (artefacts and line width behavior with angle)

agree, by default, should be define to 0
