### ISSUE TITLE
Android/Windows: list of crashing tests

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#150]
- cocos2d-x version:
- devices test on: Pocophone F1  / Windows10

ANDROID only:  
Tests chrashing "on start"
6:Chipmunk

ANDROID & WINDOWS:
Test chrashing after press "back" (some test be done)
12:yasio

WINDOWS only:

**Comment by aismann** [comment]
This is also crashing on Windows.

Test chrashing after press "back" (some test be done)
12:yasio

**Comment by halx99** [comment]
check does the latest master works

**Comment by aismann** [comment]
> 
> 
> check does the latest master works

Chipmunk and yasio works now (Windows and Android).
Thanks.

**Comment by halx99** [comment]
fix by above referenced commits
