### ISSUE TITLE
Broken tests with latest build (runs some PR/Changes before)

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#151]
Not correct on Android:

45:Node:SpritePolygon => AutoPolygon should not crash
AutoPolygon lines are not correct

**Comment by aismann** [comment]
I have a build also on Windows, shows the same behavior:
![grafik](https://user-images.githubusercontent.com/8652787/89612724-cf169a80-d880-11ea-9721-81ec5ea3641a.png)

**Comment by halx99** [comment]
I test cocos2d-x-v3, it same with egnx
![image](https://user-images.githubusercontent.com/6977319/89662300-74278680-d906-11ea-9299-0e92c3722d47.png)

**Comment by aismann** [comment]
You are right. Sorry.
I compare older build of ENGX and the result is always like the screenshot.
I close this threat.
