### ISSUE TITLE
Build APK(s): Errors while building APK. You can find the errors in the 'Messages' view:  Error message: Unknow host 'dl.google.com'

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#165]
first info: debug and arm64-v8a works:
Build APK(s)
				APK(s) generated successfully for 1 module:
				Module 'CppTests': locate or analyze the APK.

release and arm64-v8a works not: 
Error message:    Unknow host 'dl.google.com'

Any ideas?

**Comment by halx99** [comment]
it's seem caused by your network issue

**Comment by aismann** [comment]
You are right.
Android Studio needs to be "online"
I was disconnected during the apk build.
Closed.
