### ISSUE TITLE
The future of cocos2d-x

### ISSUE THREAD

**Issue by KAMIKAZEUA** [c4games/engine-x#178]
I do not want to harm such a strong desire to fix and improve something in dead cocos2d-x, but I really want to clarify this. 

It's just simply abandoned and dead as for me. 

<img width="317" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/91464507-527e4700-e895-11ea-8ff8-e4035be208d7.png">

I created a simple bug in UI which is till this day wasn't fixed and it's 2years passed like since that/

https://github.com/cocos2d/cocos2d-x/issues/18616

When people ask simple question - [where is roadmap? ](https://discuss.cocos2d-x.org/t/v4-dev-status-could-we-have-a-roadmap/49973/7) They didn't get any proper answer, just like because there is no any real roadmap. 

But they still just pretend that there is life, only I don't understand for whom, honestly.
Who is using cocos2d-x for the new games? Everyone is using the only one engine - **unity**.

When you download any SDK from analytics or ads for iOS&android  it's just presented in two versions:
 - native ObjC/Swift
 - **unitypackage**
What does this mean? 

Moreover, if you want to publish your game with some mobile publisher and tell him that your game is made on cocos2d-x - you will have a big problems in everything. Simply put, the publisher will ask you to redo everything on a unity.

**Comment by halx99** [comment]
I think, they are focus on Cocos Creator

**Comment by KAMIKAZEUA** [comment]
Yes, trying to clone unity. Waste of time.

**Comment by halx99** [comment]
Actually, we are using unity

**Comment by halx99** [comment]
And our company also have cocos2d game published, and very successfully.

**Comment by halx99** [comment]
Some improvements of this repo inspired from them

**Comment by halx99** [comment]
Such as openal for all platform, freetype stream pasing

**Comment by aismann** [comment]
@KAMIKAZEUA
Maybe you have to look here: (there is always a C++ support)
e.g. FireBase Android <https://firebase.google.com/docs/samples/#android>

If your focus more on some 3th party SDKs so you have to choose what your "important"  3th party SDK supporting at the moment.
Of course it is Unity and some others too (C++) at the moment.

**Comment by KAMIKAZEUA** [comment]
I just want to say that there’s no sense to develop such engine.. at all.

**Comment by aismann** [comment]
That's right.
There are much more things wich makes no sense but we like it.
Neverone can stop us 😏

**Comment by aismann** [comment]
@KAMIKAZEUA, you having a big challange to tell all "not Unity using" projects on the world "only Unity is the right stuff".
You get my respect for this journey :)

**Comment by KAMIKAZEUA** [comment]
Just take a look - https://discuss.cocos2d-x.org/t/is-cocos2d-x-still-being-maintained/51394

Someone asked this. But first - why to ask? Like if you ask the same question about unity? Lol.. nothing to add. 
Last remaining users asking this because there are a lot of reasons for this.. they see this and even feel. Most of other users have long given up the idea of using it. 

Notice also, that any such kind of topics on that forum always closing asap, like that one or even removed later. 
If that admin will find my these posts here) he(slackmoehrle) will remove that topic for sure. By the way that forum is like he's place, he is god here) bcs no one else from officials doing/answering anything there. 

I have no idea why he trying to convince everyone that cocos2d-x is not dead. More and more remaining users will ask this, seeing the reality.. 

People need truth! But no facts!

**Comment by aismann** [comment]
Ok. Let me say you are right. But that's your way.
Here is my way:
I like to use ENGX. I get what I want.

**Comment by mignaciolopez** [comment]
hey @KAMIKAZEUA do you know this engine? [Hazel Engine](https://github.com/TheCherno/Hazel) i think it will have a lot of future, and will have all this c++ freedom we love. I would put efforts on this engine.

**Comment by KAMIKAZEUA** [comment]
@mignaciolopez looks interesting. I hope they will do a proper editor for it!
