### ISSUE TITLE
ASTC压缩的官方库没有提供

### ISSUE THREAD

**Issue by wangsanfeng** [c4games/engine-x#190]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by halx99** [comment]
用这个工具: https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-texture-compression-tool

**Comment by halx99** [comment]
不要用mali工具，有bug，图像翻转，用官方最新工具，直接下载exe: https://github.com/ARM-software/astc-encoder/releases

**Comment by wangsanfeng** [comment]
好的，我在群里问你了。
