### ISSUE TITLE
cocostudio::Armature 无法使用 addchild后崩溃

### ISSUE THREAD

**Issue by neo-godlike** [c4games/engine-x#197]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
        cocostudio::ArmatureDataManager::getInstance()->addArmatureFileInfo("res/test/test.ExportJson");
	auto armature = cocostudio::Armature::create("test");
	armature->setPosition(ui_ccp(0.5f, 0.5f));
	armature->getAnimation()->playWithIndex(0);
	this->addChild(armature, 9);

2.

**Comment by neo-godlike** [comment]
包括 cpp-tests中UIRichTextTest.cpp 125行 官方写着todo 一旦addchild就会崩溃

**Comment by halx99** [comment]
我测试没问题呀

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/92250806-86451680-eefe-11ea-9c0b-063678716bad.png)

**Comment by halx99** [comment]
Egnx修复了这个问题的，具体看这一行: https://github.com/c4games/engine-x/blob/master/extensions/cocostudio/CCSkin.cpp#L238

**Comment by neo-godlike** [comment]
非常感谢
