### ISSUE TITLE
Try to compile "ext_glad.lib" is not a valid Win32 application.

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#204]
Steps to Reproduce:

Message:
---------------------------
Microsoft Visual Studio
---------------------------
Unable to start program 'D:\_____GitHub___\_EGNX\EGNX_0916\engine-x-master\.build\engine\external\glad\Debug\ext_glad.lib'.
D:\_____GitHub___\_EGNX\EGNX_0916\engine-x-master\.build\engine\external\glad\Debug\ext_glad.lib is not a valid Win32 application.
---------------------------
OK   
---------------------------

**Comment by halx99** [comment]
Please update 3rd libs

**Comment by aismann** [comment]
I used v68.zip

**Comment by halx99** [comment]
Please refer to the test ci build: https://ci.appveyor.com/project/halx99/engine-x/builds/35233137
it's works fine, maybe you need cleanup your build directory

**Comment by aismann** [comment]
Sorry it was my mistake.
I set the "default project to 'ext_glad'. I thought this is an executable.
