### ISSUE TITLE
Exception thrown: read access violation. **this** was nullptr.

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#212]
- cocos2d-x version: (2 hours earlier downloaded)
 
![grafik](https://user-images.githubusercontent.com/8652787/93847454-3bb9ed00-fca7-11ea-98c8-3c75406a9a37.png)

**Comment by halx99** [comment]
Does the tag alpha16 works?

**Comment by halx99** [comment]
Should be fixed by the PR: https://github.com/c4games/engine-x/pull/211

**Comment by aismann** [comment]
Thanks.
I will wait until it is part of the main branch.
No time at the moment.

**Comment by halx99** [comment]
Should fixed by latest master branch
