### ISSUE TITLE
DeviceGL Compile Error On Linux.

### ISSUE THREAD

**Issue by wzhengsen** [c4games/engine-x#216]
- cocos2d-x version:
Engine-X
- devices test on:
Ubuntu 20.04.1 LTS
- developing environments
GCC for x86_64-linux-gnu 9.30

- file:
DeviceGL.cpp-line 101

![image](https://user-images.githubusercontent.com/30433761/94017186-b6872300-fde1-11ea-909b-3d4b830482ec.png)

**Comment by halx99** [comment]
Pease tack the pr: https://github.com/c4games/engine-x/pull/217

**Comment by halx99** [comment]
see also: https://travis-ci.com/github/c4games/engine-x/builds/186413112

build requirement:
* ubuntu-18.04+
* glibc-2.27+
* New dependency: libbsd-dev: ```sudo apt-get install libbsd-dev```
