### ISSUE TITLE
project HelloCpp compiling for android : Error message: No matching configuration of project :libcocos2dx was found

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#221]
No matching configuration of project :libcocos2dx was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
  - None of the consumable configurations have attributes.

Thats means cpp-template-default is not ready for android build?

**Comment by halx99** [comment]
Well, I'm not use cpp-template-default yet, I copy cpp-empty-test and rename project name for all platforms

**Comment by aismann** [comment]
ah ok. Thanks for this hint

**Comment by halx99** [comment]
Actualy I preferred to ImGui to dev a GUI project management to do this

**Comment by aismann** [comment]
Good idea!

**Comment by halx99** [comment]
I have not test on mobile yet, only test on win & macosx

**Comment by halx99** [comment]
The ImGuiEXT can't used on mobile because it's use glfw implementation

**Comment by aismann** [comment]
Yes. Thanks.
