### ISSUE TITLE
class "cocos2d::Texture2D" has no member "initWithBackendTexture"	

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#222]
class "cocos2d::Texture2D" has no member "initWithBackendTexture"	luacocos2d	D:\_____GitHub___\_EGNX\EGNX_1002\engine-x-master\cocos\scripting\lua-bindings\auto\lua_cocos2dx_auto.cpp	2458

**Comment by halx99** [comment]
fixed by https://github.com/c4games/engine-x/commit/9f2420e9eeb1334da7220c575ce738bf572fa8b1
