### ISSUE TITLE
HttpClient Send is returning wrong response code

### ISSUE THREAD

**Issue by imtrobin** [c4games/engine-x#223]
I see your fork has the same bug

https://github.com/cocos2d/cocos2d-x/issues/20593

**Comment by halx99** [comment]
thanks, fixed

**Comment by imtrobin** [comment]
actually, I noticed android http client is also returning wrong response code (-1), I have yet to fix it

**Comment by halx99** [comment]
Good, and engine-x unify HttpClient impl with curl on all platforms

**Comment by imtrobin** [comment]
I think they are discussing to use okhttp. Hmm, I can't seem to fix it in Android, the HTTPURKLConnection.java does not return the responsecode if connect fails

**Comment by imtrobin** [comment]
The Android version is working fine, was silly mistake on my part, so the fix for the curl is good .
