### ISSUE TITLE
RenderTexture issues on iOS/macOS

### ISSUE THREAD

**Issue by etsek** [c4games/engine-x#233]
- cocos2d-x version:cocos2d-x-4.0
- devices test on: iOS 14 (iPhone), macOS 10.15.6
- developing environments
   - NDK version:
   - Xcode version: 12.0, 11.7
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Build cpp-tests, run test 41 (Node:RenderTexture)
2. Try Save Image PMA, Save Image Non-PMA: assertion failure

> Image saved image-pma-0.png
> Assert failed: reference count should be greater than 0
> Assertion failed: (_referenceCount > 0), function release, file /Users/xxxx/xxxx/cocos2d/cocos/base/CCRef.cpp, line 89.
>  

3. Try Clear to Random, Clear to Transparent: exception raised (EXC_BAD_ACCESS)

> RenderTargetMTL::Attachment RenderTargetMTL::getColorAttachment(int index) const
> {
>     if(isDefaultRenderTarget() && index == 0)
>         return {DeviceMTL::getCurrentDrawable().texture, 0};
>     auto& rb = this->_color[index];
>     return RenderTargetMTL::Attachment{static_cast<bool>(rb) ? (id<MTLTexture>)(rb.texture->getHandler()) : nil, rb.level};
> }
>

**Comment by halx99** [comment]
thanks, should be fixed by the latest commit

**Comment by etsek** [comment]
Thanks, I tested the first issue (save image) and indeed it has been fixed. The second issue however (clear) remains even after Commit 755a0fb. @halx99 can you check please?

**Comment by halx99** [comment]
I will check it later

**Comment by etsek** [comment]
Clear() works as expected now, thank you!

**Comment by halx99** [comment]
You are welcome, thanks for your report this issue
