### ISSUE TITLE
Shader applied to Spine node not working in official v. 4.0

### ISSUE THREAD

**Issue by etsek** [c4games/engine-x#234]
- cocos2d-x version: cocos2d-x-4.0
- devices test on: iPhone, Win32
- developing environments
   - NDK version:
   - Xcode version: 12.0, 11.7
   - VS version: 2019
   - browser type and version:

Steps to Reproduce:

1. Add a predefined shader to any skeletonNode in cpp-tests. For instance in SpineTest.cpp, add the following code in CoinExample::init() right before the call to scheduleUpdate(). While the sprite is properly rendered in grayscale, the Spine node in unaffected. In versions 3.17.x this functionality worked as expected.

> auto program = backend::Device::getInstance()->newProgram(
>            positionTextureColor_vert,
>            grayScale_frag);
> auto programState = new backend::ProgramState(program);
> skeletonNode->setProgramState(programState);
>    
> auto sprite = Sprite::create("Images/grossini.png");
> sprite->setPosition( Vec2(_contentSize.width/2 +100, _contentSize.height/2) );
> sprite->setProgramState(programState);
> addChild(sprite);

Shaders applied to Spine nodes do now work anymore in official v. 4.0, this is a known issue documented in https://discuss.cocos2d-x.org/t/cocos2d-4-0-create-shader-for-spine-animation/51480.  

A relevant PR has been created at  https://github.com/cocos2d/cocos2d-x/pull/20584

**Comment by halx99** [comment]
Good news

**Comment by halx99** [comment]
Does engine-x works?
Does the official v4 caused by Custom Shader?

**Comment by etsek** [comment]
Engine-x behavior is identical to official v4, i.e. shaders are not working when applied to Spine nodes. 
I'm not sure the issue is caused exclusively by custom shaders, in the above code snippet I'm using a predefined shader.

**Comment by halx99** [comment]
ok, I will check later

**Comment by halx99** [comment]
I have checked the official spine runtimes v4 implementation, it's not support custom programstate currently

**Comment by etsek** [comment]
I think there are two issues here, one has to do with the Spine runtime currently not supporting custom program state (for which Spine developers need to merge the PR fix) and the other with the fact that batching is altogether disabled for custom program types in the Cocos2d-x engine code (CCTrianglesCommand.cpp).

**Comment by halx99** [comment]
Yes, so I create a PR to re-enable custom program state batch draw

**Comment by halx99** [comment]
The PR may only improve batch draw and all program was compiled just in use time, for spine, you may needs send issue to official spine-runtimes: https://github.com/EsotericSoftware/spine-runtimes

**Comment by etsek** [comment]
There's already a PR for that issue: https://github.com/EsotericSoftware/spine-runtimes/pull/1763

**Comment by halx99** [comment]
[spine-custom-shader.zip](https://github.com/c4games/engine-x/files/5390309/spine-custom-shader.zip)
with the latest ```master``` of engine-x, the custom shader should works, see:
![image](https://user-images.githubusercontent.com/6977319/96241145-5b0d1700-0fd4-11eb-8c9b-8b08c2b7350a.png)

The test case is set spine animation HSV: https://github.com/c4games/engine-x/blob/master/tests/cpp-tests/Classes/SpineTest/SpineTest.cpp#L337

**Comment by halx99** [comment]
And I also send a PR to spine-runtimes: https://github.com/EsotericSoftware/spine-runtimes/pull/1787/files

**Comment by etsek** [comment]
Thanks! @halx99,  I pulled the latest from master and applied your Spine runtime patch and now shaders work beautifully on Spine nodes.  I think this issue is considered closed unless you want to wait for the Spine team to merge your PR.

**Comment by rh101** [comment]
Out of curiosity, have you tested displaying more than one of the same spine animation on the screen, but each spine animation uses a different custom shader or different shader uniform values?  For instance, with the HSV test case, display multiple spine animations, each having the custom HSV shader with different HSV value set for each one.  Does it work?

**Comment by halx99** [comment]
I will check later

**Comment by halx99** [comment]
@rh101 I have checked, it's display same because two spine animation merged to 1 draw batch, so needs to implement custom shader like your's ```setBatchId```

**Comment by rh101** [comment]
Fair enough.  I was hoping there was a better way to handle the batching without using the IDs, but I can't think of any other way at the moment.

**Comment by halx99** [comment]
@rh101 Hi, I use uniformID to diff final matID, see: https://github.com/c4games/cocos-re/pull/246

**Comment by rh101** [comment]
Wouldn't XXH32 be processing intensive depending on the data contained in the vertex and uniform buffers?

```
void ProgramState::updateUniformID()
{
#ifdef CC_USE_METAL
    XXH32_reset(_uniformHashState, 0);
    XXH32_update(_uniformHashState, _vertexUniformBuffer, _vertexUniformBufferSize);
    XXH32_update(_uniformHashState, _fragmentUniformBuffer, _fragmentUniformBufferSize);
    _uniformID = XXH32_digest(_uniformHashState);
#else
    _uniformID = XXH32(_vertexUniformBuffer, _vertexUniformBufferSize, 0);
#endif
#endif
}
}
```

I've never used it, so just wondering if it would be slow the larger the buffers are.

**Comment by halx99** [comment]
I think the uniform buffer size depends on shader complexity and usually it small than 256 bytes, the XXH32 so fast could be ignore, I checked the full FBO test case, the fps still fast than official v4 in my machine
* cocos-re (30fps)
* official-v4(27fps)

**Comment by halx99** [comment]
We also can provide setUniformID manually for user to avoid calculate uniformID with uniform buffer automatically, what do you think about?

**Comment by rh101** [comment]
> We also can provide setUniformID manually for user to avoid calculate uniformID with uniform buffer automatically, what do you think about?

That would be a good idea, in case the performance is affected by the XXH32 calculation.
