### ISSUE TITLE
Android x86 architecture (emulator) build failure

### ISSUE THREAD

**Issue by etsek** [c4games/engine-x#242]
- cocos2d-x version: cocos2dx-4.0
- devices test on: Android emulator x86
- developing environments
   - NDK version: 21.1.6352462
   - Android Studio: 4.1
   - browser type and version:

Steps to Reproduce:

1. Create project using cocos new, change architecture to PROP_APP_ABI=x86
2. Build fails with the following error:
ninja: error: 'C:/XXX/cocos2d/external/openal/prebuilt/android/x86/**libopenal.so**', needed by '../../../../build/intermediates/cmake/debug/obj/x86/XXX.so', missing and no known rule to make it

It seems Android x86 prebuilt library files are missing for OpenAL, Ogg under cosos2d/external.

**Comment by halx99** [comment]
Yeah, some additional of engine-x not provide android x86 .so yet.

**Comment by etsek** [comment]
Thanks @halx99, for now I'll try and compile the required libraries from source, this will be required for Ogg/Vorbis as well, correct? 
Can you suggest any other workarounds?

**Comment by halx99** [comment]
Yes, and openal

**Comment by halx99** [comment]
The armv7,arm64 build guide may helpful for you: https://simdsoft.com/notes/#ios-debug-devices

**Comment by halx99** [comment]
https://github.com/simdsoft/notes/blob/master/README.md#build-openal-soft-dependencies-for-android-platform

**Comment by etsek** [comment]
Excellent work, works as expected. Thank you!
