### ISSUE TITLE
Is there a missing c++ header file?

### ISSUE THREAD

**Issue by wzhengsen** [c4games/engine-x#253]
In the file tools/tolua/cocos2dx_studio.ini on line 30:
```ini
headers = %(cocosdir)s/extensions/libccs30/libccs30.h
```

But,There is no file named extensions/libccs30/libccs30.h.

So.If I run genbindings.py,I got a error:
![image](https://user-images.githubusercontent.com/30433761/97799709-a1b46f80-1c6a-11eb-8863-8f17fca16016.png)

**Comment by halx99** [comment]
@wzhengsen The lua binding generator should works with latest master commit: https://github.com/c4games/engine-x/commit/043d139669e680d910e6eba4284738078dc851b0, please check it
