### ISSUE TITLE
Cpp Test: 49:Node: UI ->1: GUI Dynamic Create Test  -> Any Test  crasing (e.g.: 1:EditBox Test)

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#262]
- cocos2d-x version: LATEST (from now)
Windows 10

Cpp Test: 49:Node: UI ->1: GUI Dynamic Create Test  -> Any Test  crasing (e.g.: 1:EditBox Test)

**Comment by halx99** [comment]
Does previous version works?

**Comment by aismann** [comment]
No (downloaded 20201113)

**Comment by aismann** [comment]
on android it is also not working (latest version)
