### ISSUE TITLE
"Box2DTest - Basic" => 'debug draw' is not working (need some helping hands) 

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#274]
the "debug draw methods" be commented
I'm not close enough to engine-x to add the debug draw functions

**Comment by halx99** [comment]
Just change the ````CustomCommand``` to ```CallbackCommand```, And should call b2World::setDebugDraw to set debug draw implementation, I realize the official cocos2d-x v3 doesn't call b2World::setDebugDra: https://github.com/cocos2d/cocos2d-x/blob/v3/tests/cpp-tests/Classes/Box2DTest/Box2dTest.cpp#L114
