### ISSUE TITLE
cocos2d-console Permission denied 

### ISSUE THREAD

**Issue by mignaciolopez** [c4games/engine-x#275]
only tried on macOS 10.15.7

Steps to Reproduce:

1. clone the repo
2. Enter engine-x root directory
3. Run python setup.py, restart console after finish
4. open new console
5. Run cocos --version (or run cocos, or cocos new, whatever cocos command)
(whatever folder i am at it displays same message even in Desktop or Downloads)
result:
-bash: /Users/martin/dev/engine-x/tools/cocos2d-console/bin/cocos: Permission denied 

it only works if i do python cocos.py at /engine-x/tools/cocos2d-console/bin/

**Comment by halx99** [comment]
Thanks, I will check it

**Comment by halx99** [comment]
Hello, I have test, it seems works fine:
```
deal@dealdeMac engine-x % ls -l tools/cocos2d-console/bin 
total 584
-rw-r--r--  1 deal  staff   5118 10 21 03:22 MultiLanguage.py
-rw-r--r--  1 deal  staff   4965 10 21 06:14 MultiLanguage.pyc
-rwxrwxrwx  1 deal  staff    392 10 21 07:03 cocos
-rw-r--r--  1 deal  staff     39  8 19 23:48 cocos.bat
-rw-r--r--  1 deal  staff  36874 10 21 07:03 cocos.py
-rw-r--r--  1 deal  staff  35218 10 22 02:33 cocos.pyc
-rw-r--r--  1 deal  staff   1798 10 21 06:14 cocos2d.ini
-rw-r--r--  1 deal  staff  17768  8 19 23:48 cocos_project.py
-rw-r--r--  1 deal  staff  19927 10 21 06:14 cocos_project.pyc
-rw-r--r--  1 deal  staff  16056  8 19 23:48 cocos_stat.py
-rw-r--r--  1 deal  staff  14467 10 21 06:14 cocos_stat.pyc
-rw-r--r--  1 deal  staff   2408  8 19 23:48 install.py
-rw-r--r--  1 deal  staff  94868 10 21 06:14 strings.json
-rw-r--r--  1 deal  staff   6981  8 19 23:48 utils.py
-rw-r--r--  1 deal  staff   5186 10 21 06:14 utils.pyc
deal@dealdeMac engine-x % cocos --version
cocos2d-x-4.0
Cocos Console 2.3
```

**Comment by mignaciolopez** [comment]
tried console from official cocos and it works, then i removed variables from bash_profile and tried again with engine-x, same problem. i don't know what it is. (Close the issue i don't want to waste your time) thanks.
