### ISSUE TITLE
Its very easy to use Box2D and Chipmunk2D on the same cpptest app

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#278]
What is needed to use Box2D also:

First way:
Create a class: CCPhysicsSpriteBox2D from the CCPhysicsSprite as Basic class

Second way (easier):  <<<<< this is working on my fork
Create a class: CCPhysicsSpriteBox2D from the CCPhysicsSprite (rewrite the CCPhysicsSprite)

Chipmunk2D need nothing=>using CCPhysicsSprite 

What are you mean?

**Comment by halx99** [comment]
Maybe sperate chipmunk & box2d implementation is better?

**Comment by aismann** [comment]
Yes of course!
Will be faster (hopefully) and you can add additional methods adapt to the choosen 2D physics engine.
And it will be easier to add some other 2D physics engine too.

But dont break the current API (backwards compatiblity)!
Better writting new implementation with abstract classes.

**Comment by aismann** [comment]
added
