### ISSUE TITLE
Idea:Wiki.md in the root folder is a better solution for working toghteher on wiki pages

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#288]
- engine-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:

Steps to Reproduce:

1. 
2.

**Comment by halx99** [comment]
create a uniqie repo maybe better

**Comment by aismann** [comment]
Try it.

**Comment by halx99** [comment]
create one: https://github.com/c4games/engine-x-wiki

**Comment by aismann** [comment]
perfect!
