### ISSUE TITLE
Windows: I cant rebuild jpeg=>  Building jpeg lib alone try to build:  x64-Debug (default) => is this correct?

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#289]
- engine-x version:  latest (today)

Steps to Reproduce:
CMake generation started for configuration: 'x64-Debug (default)'.

Start it on windows with Debug Win32 

Build started...
1>------ Build started: Project: jpeg, Configuration: Debug Win32 ------
1>jccolor.c
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(30,1): error C2061: syntax error: identifier '__attribute__'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(30,1): error C2059: syntax error: ';'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(32,1): error C2054: expected '(' to follow 'always_inline'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(35,1): error C2085: 'rgb_ycc_convert_internal': not in formal parameter list
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(35,1): error C2143: syntax error: missing ';' before '{'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(84,1): error C2061: syntax error: identifier '__attribute__'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(84,1): error C2059: syntax error: ';'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(86,1): error C2054: expected '(' to follow 'always_inline'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(89,1): error C2085: 'rgb_gray_convert_internal': not in formal parameter list
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(89,1): error C2143: syntax error: missing ';' before '{'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(120,1): error C2061: syntax error: identifier '__attribute__'
1>C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\external\jpeg\jccolext.c(120,1): error C2059: syntax error: ';'

Tried **glad** too (works):
================
Build started...
1>------ Build started: Project: glad, Configuration: Release Win32 ------
1>Building Custom Rule C:/Users/eismpesd/Downloads/engine-x-master/engine-x-master/external/glad/CMakeLists.txt
1>glad.c
1>glad.vcxproj -> C:\Users\eismpesd\Downloads\engine-x-master\engine-x-master\build\lib\Release\glad.lib
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

**Comment by halx99** [comment]
Don't try to build jpeg in engine-x alone, because I modify the cmake of it, and have many config in external/CMakeLists.txt

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/100707771-28817700-33e6-11eb-86bc-f77693ca458d.png)

**Comment by aismann** [comment]
ok. I never want do it. Only for debug reasons. (butyou told the solution on #290

**Comment by halx99** [comment]
ok, I will close this issue

**Comment by aismann** [comment]
> Don't try to build jpeg in engine-x alone, because I modify the cmake of it, and have many config in external/CMakeLists.txt

Maybe a Wiki entry (like: dont build external libs as standalone) is usefully?
