### ISSUE TITLE
Windows: Android cpp-test build destroy the Windows build of jpeg.lib !!!!!

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#291]
- engine-x version:  latest (20201130)
- devices test on: Windows

Steps to Reproduce:

1. Build cpptest for windows 32bit (works correct)
2.  Build cpptest for android (APK)
3. Build cpptest for windows 32bit again  (jpeg lib cant build again)   <<<<<<<<<<<<<<

see also issues:  https://github.com/c4games/engine-x/issues/289

Maybe any cpp/h files will be changed during apk creation?

At least 3 files be updated (12/1/20 6:58 AM): 
![grafik](https://user-images.githubusercontent.com/8652787/100705270-38c63180-33a7-11eb-8bf8-a866fe56e009.png)

One more hint:
On older engine-x versions jpeg.lib was prebuilt.

**Comment by halx99** [comment]
The reason is: the configue_file(jconfig.h.in at same directory)
