### ISSUE TITLE
Need a tip:   pugi::xml_parse_result result = doc.load_file(filename.c_str() relative path is not working

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#299]
What is missing?
Original path on windows: "D:/dev/projects/Debug/Resources/maps/map_start.xml"

full path is working:
doc.load_file("D:/dev/projects/Debug/Resources/maps/map_start.xml")

**_relative path is not working !!!! 
doc.load_file("maps/map_start.xml")_**

This kind of reative path is working (why not above?):
auto parentItems = SpriteBatchNode::create("graphics/items.png", 100);

**Comment by halx99** [comment]
Because engine-x has default search path to Resources on windows

**Comment by halx99** [comment]
pugixml no serach path, so the relative should based on working ditectory, not Resources

**Comment by aismann** [comment]
thanks
