### ISSUE TITLE
Some stuff creating own project: Unable to start program 'D:\dev\projects\myGame\build\Debug\ALL_BUILD'.

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#301]
- engine-x version: latest
---------------------------
Microsoft Visual Studio
---------------------------
Unable to start program 'D:\dev\projects\myGame\build\Debug\ALL_BUILD'.
The system cannot find the file specified.
---------------------------
OK   
---------------------------

**Comment by halx99** [comment]
I saw you try to start target ALL_BUILD, don't do this
