### ISSUE TITLE
Bullet Physics release  3.07 this 11 days ago

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#305]
3.07: Merge pull request #3090 from ErikGartner/master

@erwincoumans erwincoumans released this 11 days ago · 9 commits to master since this release

This updated Bullet Physics release was used for the
"Learning Agile Robotic Locomotion Skills by Imitating Animals" research., led by Jason Peng.

**Comment by halx99** [comment]
Sync finished: 
https://github.com/c4games/engine-x/commit/e273d77c964c59177917ce65f1b7efa5236bfbc5
