### ISSUE TITLE
engine-x\cocos\audio\src\AudioPlayer.cpp => "ALOGV(..."   should be changed to "ALOGVV(..." ?

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#317]
ALOGV is printing lines like this: V/AudioPlayer (160): AudioPlayer::play2d, _alSource: 3, player id=3
But I dont like it on my CCLOG debug output too.
ALOGVV is silent  (be ALOGV lines forgotten to change?).
Maybe other files too?

**Comment by halx99** [comment]
Yes, you can do it

**Comment by aismann** [comment]
I did some deeper look into the cocos2d sources, there are so much "debug outputs".
To much work. I close it.
