### ISSUE TITLE
Crash on ParticleBatchNode::updateProgramStateTexture()

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#318]
engine-x: latest version (build on windows)

38:Node: Particles => 44 ...  chrashing

![grafik](https://user-images.githubusercontent.com/8652787/105895526-e9525980-6015-11eb-9899-18e945237e6f.png)

**Comment by halx99** [comment]
Should be fixed by latest commit, thanks for your report.

**Comment by aismann** [comment]
Works. Thanks.
