### ISSUE TITLE
vs2019 win32 release mode build error.

### ISSUE THREAD

**Issue by denghe** [c4games/engine-x#323]
- engine-x version: 2021.2.5
- devices test on: win10
- developing environments
   - VS version:2019

Steps to Reproduce:

1. git clone enginex & cmake ..... win32 ( offical tutorial )
2. vs Release compile ( Debug is ok )
Build started...
1>------ Build started: Project: simd-objs, Configuration: Release Win32 ------
2>------ Build started: Project: COPY_LUA-lua-empty-test, Configuration: Release Win32 ------
3>------ Build started: Project: SYNC_RESOURCE-HelloCpp, Configuration: Release Win32 ------
4>------ Build started: Project: COPY_LUA-lua-tests, Configuration: Release Win32 ------
5>------ Build started: Project: SYNC_RESOURCE-cpp-empty-test, Configuration: Release Win32 ------
6>------ Build started: Project: SYNC_RESOURCE-cpp-tests, Configuration: Release Win32 ------
7>------ Build started: Project: SYNC_RESOURCE-fairygui-tests, Configuration: Release Win32 ------
8>------ Build started: Project: SYNC_RESOURCE-lua-empty-test, Configuration: Release Win32 ------
9>------ Build started: Project: SYNC_RESOURCE-lua-tests, Configuration: Release Win32 ------
10>------ Skipped Build: Project: jsimdcfg, Configuration: Release Win32 ------
10>Project not selected to build for this solution configuration 
6>Copying resources for cpp-tests ...
4>Copying lua scripts ...
5>Copying resources for cpp-empty-test ...
4>  Compiling C:/Codes/engine-x/tests/lua-tests/project/../src\AccelerometerTest\AccelerometerTest.lua
4>Traceback (most recent call last):
4>  File "C:/Codes/engine-x/cmake/scripts/sync_folder.py", line 92, in <module>
4>    sync_folder(args.src_dir, args.dst_dir, args.luajit, need_compile)
4>  File "C:/Codes/engine-x/cmake/scripts/sync_folder.py", line 67, in sync_folder
4>    sync_folder(src, dst, luajit, need_compile)
4>  File "C:/Codes/engine-x/cmake/scripts/sync_folder.py", line 67, in sync_folder
4>    sync_folder(src, dst, luajit, need_compile)
4>  File "C:/Codes/engine-x/cmake/scripts/sync_folder.py", line 58, in sync_folder
4>    compile_if_newer(src_dir, dst_dir, luajit)
4>  File "C:/Codes/engine-x/cmake/scripts/sync_folder.py", line 41, in compile_if_newer
4>    compile_lua(src, dst, cmd)
4>  File "C:/Codes/engine-x/cmake/scripts/sync_folder.py", line 30, in compile_lua
4>    ret = subprocess.call(command, shell=True, cwd = os.path.dirname(luajit_command))
4>  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 339, in call
4>    with Popen(*popenargs, **kwargs) as p:
4>  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 800, in __init__
4>    restore_signals, start_new_session)
4>  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 1207, in _execute_child
4>    startupinfo)
4>OSError: [WinError 123] 文件名、目录名或卷标语法不正确。
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: The command "setlocal

**Comment by denghe** [comment]
![image](https://user-images.githubusercontent.com/3364637/106988622-34edcb80-67ab-11eb-89ee-15088c3b2179.png)

**Comment by halx99** [comment]
Do you installed python?

**Comment by denghe** [comment]
Debug mode build success that mean py installed?

**Comment by denghe** [comment]
![image](https://user-images.githubusercontent.com/3364637/106991605-8ef18f80-67b1-11eb-87aa-79394a4e8e25.png)

**Comment by denghe** [comment]
4>Done building project "COPY_LUA-lua-tests.vcxproj" -- FAILED.
2>Done building project "COPY_LUA-lua-empty-test.vcxproj" -- FAILED.

others no problem

**Comment by denghe** [comment]
19>------ Skipped Build: Project: INSTALL, Configuration: Release Win32 ------
19>Project not selected to build for this solution configuration 
========== Build: 15 succeeded, 2 failed, 35 up-to-date, 2 skipped ==========

**Comment by halx99** [comment]
The github action for win32 build type is `Release`, and it works fine, I don't know why fail on your machine.

**Comment by halx99** [comment]
You can try disable lua compiling for release mode

**Comment by halx99** [comment]
fixed by latest commit: https://github.com/c4games/engine-x/commits/master
