### ISSUE TITLE
Error	MSB3073	The command "setlocal  (first build an a new computer get this error)

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#335]
Any idea why?

Error	MSB3073	The command "setlocal
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E echo "    copying to D:/______/GitHub/engine-x/build/bin/cpp-empty-test/Debug/Resources"
if %errorlevel% neq 0 goto :cmEnd
PYTHON_COMMAND-NOTFOUND D:/______/GitHub/engine-x/cmake/scripts/sync_folder.py -s D:/______/GitHub/engine-x/tests/cpp-empty-test/Resources -d D:/______/GitHub/engine-x/build/bin/cpp-empty-test/Debug/Resources
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 9009.	SYNC_RESOURCE-cpp-empty-test	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	155

**Comment by halx99** [comment]
Your python not install properly or delete CmakeCache.txt and regenrate sln again

**Comment by halx99** [comment]
Please ensure your python bin directory in the system env `PATH` before run cmake to generate .sln

**Comment by aismann** [comment]
I will test it later. Info comes.

**Comment by aismann** [comment]
Thanks works now.

**Comment by halx99** [comment]
you are welcome
