### ISSUE TITLE
Is there some way to compile for android by command line, is cocos console command supported ?

### ISSUE THREAD

**Issue by Joilnen** [c4games/engine-x#338]
- engine-x version: 273cd3c7c30dfdd0f2a34d11cab82f54977758a9
- devices test on: linux cross compile to android using cocos command
- developing environments
   - NDK version: r21e
  - . cocos new -d ~ -e . -l cpp TestEngineX
  -  "inside TestEngineX dir " cocos compile -p android "got errors, you can see in attached file" 
[enginex_errors.txt](https://github.com/c4games/engine-x/files/6336916/enginex_errors.txt)

**Comment by halx99** [comment]
the latest should works, please refer to github action for buiding android on ubuntu linux

**Comment by Joilnen** [comment]
I got this error after

cmake --version
cmake version 3.20.1

"cocos compile -p android" 


Parsing /home/joilnen/Android/Sdk/sources/android-29/package.xml
Parsing /home/joilnen/Android/Sdk/sources/android-30/package.xml
Parsing /home/joilnen/Android/Sdk/system-images/android-22/google_apis/x86/package.xml
Parsing /home/joilnen/Android/Sdk/tools/package.xml
SDK initialized in 8045 ms
debug|native No CMake version was specified in build.gradle. Choosing a suitable version.
debug|native Trying to locate CMake in local SDK repository.
debug|native CMake '3.10.2' found in SDK did not match requested version '3.6.0'.
debug|native - CMake found in SDK at '/home/joilnen/Android/Sdk/cmake/3.6.4111459' had version '3.6.0'
release|native No CMake version was specified in build.gradle. Choosing a suitable version.
release|native Trying to locate CMake in local SDK repository.
release|native CMake '3.10.2' found in SDK did not match requested version '3.6.0'.
release|native - CMake found in SDK at '/home/joilnen/Android/Sdk/cmake/3.6.4111459' had version '3.6.0'
All projects evaluated.
Selected primary task 'assembleDebug' from project :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':TestEngineX:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':TestEngineX:debugCompileClasspath'.
   > Could not resolve project :libcocos2dx.
     Required by:
         project :TestEngineX
      > Unable to find a matching configuration of project :libcocos2dx: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Error running command, return code: 1.

**Comment by halx99** [comment]
I have check the log from github action, and there is no `debug|native CMake '3.10.2' found in SDK did not match requested version '3.6.0'.`, instead the log is:
```txt
 CMake found in SDK at '/home/runner/work/engine-x/android-sdk/cmake/3.10.2.4988404' had version '3.10.2'
No CMake version was specified in build.gradle. Using default version 3.10.2.
```

**Comment by halx99** [comment]
Maybe engine-x require 3.10+ for build android, chould try pull latest version of engine-x and recreate your test project, then try `cocos compile -p android` again

**Comment by Joilnen** [comment]
It works fine in cocos2d-x 3.17.1.2 but still not working in engineX

Creating configuration testReleaseCompileOnly
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
Parsing the SDK, no caching allowed
SDK initialized in 93 ms
debug|native No CMake version was specified in build.gradle. Choosing a suitable version.
debug|native Trying to locate CMake in local SDK repository.
debug|native CMake '3.10.2' found in SDK did not match requested version '3.6.0'.
debug|native - CMake found in SDK at '/home/joilnen/Android/Sdk/cmake/3.6.4111459' had version '3.6.0'
release|native No CMake version was specified in build.gradle. Choosing a suitable version.
release|native Trying to locate CMake in local SDK repository.
release|native CMake '3.10.2' found in SDK did not match requested version '3.6.0'.
release|native - CMake found in SDK at '/home/joilnen/Android/Sdk/cmake/3.6.4111459' had version '3.6.0'
All projects evaluated.
Selected primary task 'assembleDebug' from project :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':TestEngineX:externalNativeBuildDebug'.
> Could not resolve all task dependencies for configuration ':TestEngineX:debugRuntimeClasspath'.
   > Could not resolve project :libcocos2dx.
     Required by:
         project :TestEngineX
      > Unable to find a matching configuration of project :libcocos2dx: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Error running command, return code: 1.

**Comment by halx99** [comment]
I don't known why your gradle always choose cmake 3.6 in android sdk, the cmake 3.6 no longer supported by engine-x

**Comment by halx99** [comment]
By the way, what's your android studio version?

**Comment by halx99** [comment]
Please follow steps:
- pull the latest commit: https://github.com/c4games/engine-x/commit/49c1318fc1bb55b926292780974e6484fb33e83e
- ensure run `setup.py` of engine-x (make sure the command `cocos` create project from engine-x
- recreate your test project
- run `cocos compile -p android` again

**Comment by halx99** [comment]
Note: when use sdk installed by android studio, will always choose cmake 3.6 to build if `app/build.gradle` not specific cmake version.

**Comment by Joilnen** [comment]
I don't use sdk installed from android studio, could you to check how cocos2d-3.17.2 works, is seems works only checking environments vars

**Comment by halx99** [comment]
I have setup engine-x build env on my aliyun ubuntu linux, everything looks good

**Comment by halx99** [comment]
cocos2d-x-3.17.2 can works on cmake 3.6

**Comment by Joilnen** [comment]
But EngineX doesn't ?
I had cmake 3.6 3.10 and 3.18 in android sdk and 3.10 in native it is arch

**Comment by halx99** [comment]
Yeah, so recently, I set cmake minimal require version to 3.10.0+ at `app/build.gradle`, so If you recreate your test project, the android sdk will choose cmake-3.10.2

**Comment by halx99** [comment]
The github android build action use ubuntu-18.04, and I also test on my aliyun ubuntu is 20.04

**Comment by halx99** [comment]
The follow is my steps to install android-ndk & sdk on my own ubuntu server 20.04:
1. Prepare adt dir:
```sh
sudo su
mkdir /opt/adt
cd /opt/adt
```
2. install ndk
```sh
cd /opt/adt
wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
unzip android-ndk-r21e-linux-x86_64.zip
```
3. install sdk
```sh
cd /opt/adt
https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
unzip commandlinetools-linux-6858069_latest.zip
mkdir -p ~/.android && touch ~/.android/repositories.cfg
./cmdline-tools/bin/sdkmanager --verbose --sdk_root=/opt/adt/android-sdk "platform-tools" "cmdline-tools;latest" "platforms;android-28" "build-tools;29.0.2"
```
4. Add to env var ANDROID_NDK, ANDROID_SDK
```sh
vim ~/.bashrc
# add follow 2 lines to end of the file .bashrc
export ANDROID_NDK=/opt/adt/android-ndk-r21e
export ANDROID_SDK=/opt/adt/android-sdk
source ~/.bashrc
```

**Comment by halx99** [comment]
Since above steps works on a new ubuntu-20.04 os image run on vmware, I close this issue, if you have any other question, please feel free to reply at here

**Comment by Joilnen** [comment]
working fine now, I am sorry the long time to report it, thank you
