### ISSUE TITLE
Linkage problems to compile for Linux by cocos command line

### ISSUE THREAD

**Issue by Joilnen** [c4games/engine-x#344]
- engine-x version: ce6117fa65a012dd289e3f3b7b67856064908643
- devices test on: linux x86_64
after the command "cocos run -p linux"

[log.txt](https://github.com/c4games/engine-x/files/6373954/log.txt)

**Comment by halx99** [comment]
I just run on my vmware ubuntu-20.04, it seems works well:
![image](https://user-images.githubusercontent.com/6977319/116033448-fe319e00-a693-11eb-85c8-87c1d405e8f5.png)

**Comment by halx99** [comment]
And engine-x already remove fmod from linux build, maybe you use old cocos2d-x edition for create your test project.

**Comment by Joilnen** [comment]
you are right I was running the cocos old script thanks it is working fine
