### ISSUE TITLE
Color incorrect in android simlulators(Xiaoyao, Tencent, Yeshen with DirectX)

### ISSUE THREAD

**Issue by halx99** [c4games/engine-x#41]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/74001452-a0d60200-49a6-11ea-8fd9-a67d022a7b9e.png)

**Comment by weiwest** [comment]
select OpenGL can fix this problem

**Comment by halx99** [comment]
It's seems the G,B color is missing, only R value works at shader.

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/75104557-b05f7700-5645-11ea-9638-ce4da8952f1b.png)
see the snapshot, I change to fixed color with R=0.0,  I just see a black screen when run on simulator with (directx render mode)

**Comment by halx99** [comment]
I think, I got it.

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/75114715-6dc48b80-5693-11ea-9afa-8b490a36af25.png)
