### ISSUE TITLE
V4 cocos2d::extension::ScrollView and cocos2d::extension::TableView not clipping

### ISSUE THREAD

**Issue by neo-godlike** [c4games/engine-x#97]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2. 
its fixed by https://github.com/cocos2d/cocos2d-x/pull/20426
fyi

**Comment by halx99** [comment]
thanks, I will check it later

**Comment by halx99** [comment]
Do you have time to send this the PR to engine-x directly?

**Comment by halx99** [comment]
@neo-godlike Hello, I create a pr #100 , please review it

**Comment by neo-godlike** [comment]
@halx99 sorry. am still working. But i'll try to make time for this project. I appreciate your idea. great job!
